nome = str(input('Digite seu nome completo: ')).strip()
print('Analisando seu nome...')
print('Seu nome em maiúsculas é {}.'.format(nome.upper()))
print('Seu nome em minúsculas é {}.'.format(nome.lower()))
print('seu nome tem ao todo {} letras.'.format(len(nome)-nome.count(' ')))
#print('Seu primeiro nome possui {} letras.'.format(nome.find(' ')))
nome = nome.split()
print('Seu primeiro nome é {} e ele possui {} letras.'.format(nome[0], len(nome[0])))