lanche = ('Burger', 'Suco', 'Pizza', 'Pudim') #entre () - Variavel composta TUPLA / funciona tbm sem os ()
print(lanche[-2])
print(lanche[1])
print(lanche[1:3])
print(lanche[2:])
print(lanche[:2])
print(lanche[-2:])
print(lanche[3:1:-1])

print(sorted(lanche))